from fastapi import FastAPI, Request
from fastapi.responses import HTMLResponse
from fastapi.staticfiles import StaticFiles
import struct
import os
import json
import pandas as pd
import uvicorn
import mmap
import subprocess

app = FastAPI()

# --- CONFIG ---
# FILE_PATH = "data/market_data.bin"
CATALOG_FILE = "data/catalog.json"
RECORD_SIZE = 32
FORMAT = '<QiiiiII'

# --- HELPER: LOAD DATA (Cached in Memory) ---
# In a real app, you'd use Redis. Here we just keep it in RAM.
df_cache = None

def load_catalog():
    with open(CATALOG_FILE, "r") as f:
        return json.load(f)

def get_matching_partitions(start, end):
    catalog = load_catalog()

    matching = []

    for partition in catalog:
        if partition["end"] >= start and partition["start"] <= end:
            matching.append(partition)

    return matching

def read_partition(file_path):
    records = []
    
    with open(file_path, "rb") as f:
        # Map the entire file into virtual memory
        # ACCESS_READ prevents us from accidentally modifying the binary file
        with mmap.mmap(f.fileno(), 0, access=mmap.ACCESS_READ) as mm:
            file_size = os.path.getsize(file_path)
            offset = 0
            
            # Loop through the memory-mapped region
            # We check file_size to ensure we don't read past the end
            while offset + RECORD_SIZE <= file_size:
                # Slice the memory view instead of calling f.read()
                # This is instantaneous and doesn't copy data to a new buffer
                data = mm[offset : offset + RECORD_SIZE]
                
                if not data:
                    break

                ts, o, h, l, c, v, crc = struct.unpack(FORMAT, data)

                records.append({
                    "x": ts * 1000,
                    "o": o / 10000.0,
                    "h": h / 10000.0,
                    "l": l / 10000.0,
                    "c": c / 10000.0
                })
                    
                offset += RECORD_SIZE

    return records

def get_data(start=None, end=None):
    global df_cache
    # if df_cache is None:
    #     records = []
    #     with open(FILE_PATH, "rb") as f:
    #         while True:
    #             data = f.read(RECORD_SIZE)
    #             if not data: break
    #             ts, o, h, l, c, v, crc = struct.unpack(FORMAT, data)
    #             # Chart.js needs milliseconds
    #             records.append({
    #                 "x": ts * 1000, 
    #                 "o": o / 10000.0, 
    #                 "h": h / 10000.0, 
    #                 "l": l / 10000.0, 
    #                 "c": c / 10000.0
    #             })
    #     df_cache = records
    # return df_cache
    if start is None and end is None and df_cache is not None:
        return df_cache
    records = []

    # partitions = load_catalog()
    if start is not None and end is not None:
        partitions = get_matching_partitions(start, end)
        print("MATCHING PARTITIONS:", partitions)
    else:
        partitions = load_catalog()

    for partition in partitions:
        partition_records = read_partition(partition["file"])
        records.extend(partition_records)

    if start is None and end is None:
        df_cache = records

    return records

# --- HELPER: CALL THE C ANALYZER ---
def analyze_symbol(symbol: str, period: int):
    """
    Calls the native C analyzer to compute indicators (SMA).
    """
    cmd = ["./analyzer", symbol, str(period)]
    
    # Execute the C binary
    result = subprocess.run(cmd, capture_output=True, text=True)
    
    if result.returncode != 0:
        raise HTTPException(f"Analyzer failed: {result.stderr}")
    
    # Parse the JSON output generated by C
    return json.loads(result.stdout)

def get_sma_data(symbol: str, period: int):
    """
    Calls the native C analyzer to compute SMA.
    """
    cmd = ["./analyzer", symbol, str(period)]
    
    # Execute the C Worker
    try:
        result = subprocess.run(cmd, capture_output=True, text=True)
    except Exception as e:
        return {"error": str(e)}
    
    #  # Parse the stdout (JSON string) into Python objects
    # C handles the math; Python handles the Data Structure.
    return json.loads(result.stdout)

# --- ROUTE 1: SERVE THE HTML ---
@app.get("/", response_class=HTMLResponse)
async def read_root():
    with open("template/index.html", "r") as f:
        return f.read()

# --- ROUTE 2: API ENDPOINT (Returns JSON) ---
@app.get("/api/data")
# async def get_api_data():
#     return get_data()
async def get_api_data(start: int = None, end: int = None):
    print("API RANGE:", start, end) 
    return get_data(start, end)

# --- ROUTE 3: ANALYSIS ENDPOINT (Calls C) ---
@app.get("/api/indicators/sma")
async def get_sma(symbol: str = "AAPL", period: int = 20):
    try:
        # return {"data": analyze_symbol(symbol, period)}
        return get_sma_data(symbol, period)
    except Exception as e:
        raise HTTPException(f"Analysis failed: {e}")

if __name__ == "__main__":
    uvicorn.run("main:app", host="127.0.0.1", port=8000)